Revert "prometheus: point prometheus.svc.esams to prometheus3001"
This reverts commit 77d37c184cc345e9044f8e96c4ac5abf2f4704c7.

Reason for revert: authdns-update erroring out with the below, will retry later.

"error: plugin_geoip: Invalid resource name 'disc-releases' detected from zonefile lookup
error: Name 'releases.discovery.wmnet.': resolver plugin 'geoip' rejected resource name 'disc-releases'"

Change-Id: I80587e723c84f1b21e829789b286f9469ba88323