Revert "netbox: update netbox so that its active/active"
This reverts commit a21746632e4b7fb90cb4745ce5fd6b7d678ef492.

Reason for revert: recived error

Change-Id: I48601c3ece40f581aaa24746c6ce02687e84e816
error: plugin_geoip: Invalid resource name 'disc-netbox' detected from zonefile lookup
error: Name 'netbox.discovery.wmnet.': resolver plugin 'geoip' rejected resource name 'disc-netbox'