decom mw2256.codfw.wmnet
the decom cookbook said:

**Not all affected DC(s) have been migrated to automatic DNS,
a manual patch to the operations/dns repository is required**
ERROR: some step failed, check the task updates.

This is supposed to be that patch.

Bug: T263065
Change-Id: I6dc0a684a83c20fe2b225d63bfb7bcfe9ed41202