Revert "Add shellbox to discovery"
This reverts commit 779bada49cc9993a3cff014786c3d9f1199298a5.

Reason for revert: authdns is not happy

Change-Id: If9b2551a87dfb32bd83b38a4709da53248a5d7cb
error: plugin_geoip: Invalid resource name 'disc-shellbox' detected from zonefile lookup
error: Name 'shellbox.discovery.wmnet.': resolver plugin 'geoip' rejected resource name 'disc-shellbox'