Revert "netbox: create discovery record for netbox"
This reverts commit 33e3ee6395f94f2a9461c64a4a968923ddb3e93c.

Reason for revert: 
error: plugin_metafo: Invalid resource name 'disc-netbox' detected from zonefile lookup
error: Name 'netbox.discovery.wmnet.': resolver plugin 'metafo' rejected resource name 'disc-netbox'

Change-Id: If1c01d02a3ee7e9b80937b29348db94dd4811c7c